# Generated by Django 6.0 on 2025-12-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spaceships',
            options={'verbose_name': 'Корабль', 'verbose_name_plural': 'Корабли'},
        ),
        migrations.RemoveField(
            model_name='spaceships',
            name='mglt',
        ),
        migrations.AlterField(
            model_name='spaceships',
            name='cargo_capacity',
            field=models.TextField(blank=True, max_length=256, verbose_name='Грузоподъёмность'),
        ),
        migrations.AlterField(
            model_name='spaceships',
            name='consumables',
            field=models.TextField(blank=True, max_length=256, verbose_name='Объём прод. запасов'),
        ),
        migrations.AlterField(
            model_name='spaceships',
            name='cost_in_credits',
            field=models.TextField(blank=True, max_length=256, verbose_name='Стоимость в кредитах'),
        ),
        migrations.AlterField(
            model_name='spaceships',
            name='crew',
            field=models.TextField(blank=True, max_length=256, verbose_name='Экипаж'),
        ),
        migrations.AlterField(
            model_name='spaceships',
            name='hyperdrive_rating',
            field=models.TextField(blank=True, max_length=256, verbose_name='Рейтинг гипердвигателя'),
        ),
        migrations.AlterField(
            model_name='spaceships',
            name='max_atmosphering_speed',
            field=models.TextField(blank=True, max_length=256, verbose_name='Макс. скорость'),
        ),
        migrations.AlterField(
            model_name='spaceships',
            name='passengers',
            field=models.TextField(blank=True, max_length=256, verbose_name='Пассажиры'),
        ),
        migrations.AddField(
            model_name='spaceships',
            name='MGLT',
            field=models.TextField(blank=True, max_length=256, verbose_name='MGLT'),
        ),
    ]
