# Generated by Django 6.0 on 2025-12-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.RemoveField(
            model_name='people',
            name='film_ids',
        ),
        migrations.RemoveField(
            model_name='people',
            name='starship_ids',
        ),
        migrations.RemoveField(
            model_name='people',
            name='vehicle_ids',
        ),
        migrations.AlterField(
            model_name='people',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='people',
            name='mass',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса'),
        ),
    ]
